name: Introduction of GitHub Action Workflows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Print GitHub Actor
        run: echo "Triggered by ${{ github.actor }}"

      - name: Print System User
        run: echo "Runner user is $USER"
